version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ebooking_db
    environment:
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
      POSTGRES_DB: e_booking
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: ebooking_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ebooking.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
    restart: always

volumes:
  db_data:
